version: '3.7'

services:
    backup-bot:
        build: .
        command: npm start
        env_file: .env
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: credentials.json
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
